# 提供云环境冒着风险方便大家演示用，切勿修改配置，开发定位错误和大家使用比较麻烦，望理解。
# 如果要改配置搭建下本地环境哈，步骤在项目说明README
# 项目对你有帮助麻烦给个❤，感激不尽！https://github.com/hxrui
spring:
  redis:
    database: 0
    host: www.youlai.tech
    port: 6379
    password: 123456
  elasticsearch:
    rest:
      uris: ["http://g.youlai.tech:9200"]
      cluster-nodes:
        - g.youlai.tech:9200
  cloud:
    sentinel:
      enabled: false
      eager: true # 取消控制台懒加载，项目启动即连接Sentinel
      transport:
        client-ip: localhost
        dashboard: localhost:8080
      datasource:
        # 降级规则
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: degrade    
 

weapp:
  appid: wx99a151dc43d2637b
  secret: a09605af8ad29ca5d18ff31c19828f37

# 全局参数设置
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  sentinel:  # 开启feign对sentinel的支持
    enabled: false 
